# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2479aae492881c584110287f0b62dd27f2ec1390ec52ac6796a56d095dda3c4d637087a3225a45642aa26b67cf3240626f1b7f78a324f5867f4ce28fd2784b66

test:
  secret_key_base: 80a52efaf84cf992888057a2031d27241d1038505cea369cdc138fb871db90212ab0007a3dcf4d701617f87e850aa3569bd51b319b03036b5212d2509ece35fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
